version: '3'

# This is for development purposes
services:
  uberlike-gateway:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ../volumes/gateway:/home/java/uberlike-gateway
    networks:
      - consul

  consul-server:
    image: hashicorp/consul:1.11.2
    container_name: consul-server
    restart: always
    volumes:
      - ../volumes/consul/server1.json:/consul/config/server1.json:ro
      - ../volumes/consul/certs/:/consul/config/certs/:ro
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=1"

  consul-client:
    image: hashicorp/consul:1.11.2
    container_name: consul-client
    restart: always
    volumes:
      - ../volumes/consul/client.json:/consul/config/client.json:ro
      - ../volumes/consul/certs/:/consul/config/certs/:ro
    networks:
      - consul
    command: "agent"

  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411'
    networks:
      - consul

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    ports:
      - 3762:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - type: bind
        source: ../volumes/keycloak
        target: /opt/keycloak/data/import
    networks:
      - consul
    command: -v start-dev --import-realm
    depends_on:
      - postgres

  postgres:
    image: postgres:16.0-alpine
    volumes:
      - ../volumes/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - consul

networks:
  consul:
    driver: bridge
